<?php

namespace Database\Seeders;

use App\Models\Broker;
use App\Models\Shipment;
use App\Models\ShipmentStatusList;
use App\Models\ShipmentType;
use Illuminate\Database\Seeder;

class ShipmentSeeder extends Seeder
{
    public function run(): void
    {
        $processing = ShipmentStatusList::where('status_name', 'Processing')->first();
        $completed = ShipmentStatusList::where('status_name', 'Completed')->first();
        $pending = ShipmentStatusList::where('status_name', 'Pending')->first();
        $failed = ShipmentStatusList::where('status_name', 'Failed')->first();

        $sea = ShipmentType::where('shipment_type_name', 'Sea')->first();
        $air = ShipmentType::where('shipment_type_name', 'Air')->first();
        $land = ShipmentType::where('shipment_type_name', 'Land')->first();

        $grab = Broker::where('broker_name', 'Grab Philippines')->first();
        $lalancove = Broker::where('broker_name', 'Lalancove')->first();
        $angkas = Broker::where('broker_name', 'Angkas')->first();
        $movelt = Broker::where('broker_name', 'Movelt')->first();
        $joyride = Broker::where('broker_name', 'Joyride')->first();
        $lbc = Broker::where('broker_name', 'LBC')->first();

        $shipments = [
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-488',
                'brand' => 'Brumate',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2003-09-25',
                'broker_id' => $grab?->broker_id,
                'brand_manager' => 'Matthew Andre Corral',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-489',
                'brand' => 'Fendi Casa',
                'incoterm' => 'FCA',
                'actual_time_of_arrival' => '2003-12-20',
                'broker_id' => $lalancove?->broker_id,
                'brand_manager' => 'Shannen Salvatera',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-490',
                'brand' => 'Hunter Douglas',
                'incoterm' => 'FCA',
                'actual_time_of_arrival' => '2003-05-27',
                'broker_id' => $angkas?->broker_id,
                'brand_manager' => 'Terrenz Cubacub',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-491',
                'brand' => 'TechnoGym',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2002-05-23',
                'broker_id' => $movelt?->broker_id,
                'brand_manager' => 'Gavin Lorenzo Castro',
                'shipment_type_id' => $air->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-492',
                'brand' => 'Philips Personal Care',
                'incoterm' => 'FOB',
                'actual_time_of_arrival' => '2003-12-22',
                'broker_id' => $joyride?->broker_id,
                'brand_manager' => 'Jaslein Zynah Dueñas',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-493',
                'brand' => 'Villeroy & Boch',
                'incoterm' => 'FCA',
                'actual_time_of_arrival' => '2004-04-28',
                'broker_id' => $grab?->broker_id,
                'brand_manager' => 'Christian Jerard Abella',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-494',
                'brand' => 'B&B Italia',
                'incoterm' => 'FOB',
                'actual_time_of_arrival' => '2004-04-04',
                'broker_id' => $joyride?->broker_id,
                'brand_manager' => 'Angela Luisse Briones',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-495',
                'brand' => 'DMC',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2004-04-17',
                'broker_id' => $lbc?->broker_id,
                'brand_manager' => 'Reich Alexandria Balubal',
                'shipment_type_id' => $land->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-496',
                'brand' => 'Boffi',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2003-12-29',
                'broker_id' => $movelt?->broker_id,
                'brand_manager' => 'Anvil Dumaual',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-497',
                'brand' => 'Philips Personal Care',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2004-05-11',
                'broker_id' => $grab?->broker_id,
                'brand_manager' => 'XXXXXXXX',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-498',
                'brand' => 'Poltrona Frau',
                'incoterm' => 'FOB',
                'actual_time_of_arrival' => '2004-06-15',
                'broker_id' => $lalancove?->broker_id,
                'brand_manager' => 'Maria Santos',
                'shipment_type_id' => $air->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-499',
                'brand' => 'Versace',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2004-07-08',
                'broker_id' => $angkas?->broker_id,
                'brand_manager' => 'Juan Dela Cruz',
                'shipment_type_id' => $land->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-500',
                'brand' => 'Giorgio Armani',
                'incoterm' => 'FCA',
                'actual_time_of_arrival' => '2004-08-12',
                'broker_id' => $movelt?->broker_id,
                'brand_manager' => 'Rosa Garcia',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-501',
                'brand' => 'Baccarat',
                'incoterm' => 'FOB',
                'actual_time_of_arrival' => '2004-09-03',
                'broker_id' => $joyride?->broker_id,
                'brand_manager' => 'Carlos Mendez',
                'shipment_type_id' => $air->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-502',
                'brand' => 'Louis Vuitton',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2004-10-19',
                'broker_id' => $lbc?->broker_id,
                'brand_manager' => 'Patricia Reyes',
                'shipment_type_id' => $land->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-503',
                'brand' => 'Hermès',
                'incoterm' => 'FCA',
                'actual_time_of_arrival' => '2004-11-07',
                'broker_id' => $grab?->broker_id,
                'brand_manager' => 'Miguel Santos',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-504',
                'brand' => 'Gucci',
                'incoterm' => 'FOB',
                'actual_time_of_arrival' => '2004-12-22',
                'broker_id' => $lalancove?->broker_id,
                'brand_manager' => 'Lucia Fernandez',
                'shipment_type_id' => $air->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-505',
                'brand' => 'Prada',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2005-01-14',
                'broker_id' => $angkas?->broker_id,
                'brand_manager' => 'Adriana Silva',
                'shipment_type_id' => $land->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-506',
                'brand' => 'Chanel',
                'incoterm' => 'FCA',
                'actual_time_of_arrival' => '2005-02-28',
                'broker_id' => $movelt?->broker_id,
                'brand_manager' => 'Vincent Laurent',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-507',
                'brand' => 'Rolex',
                'incoterm' => 'FOB',
                'actual_time_of_arrival' => '2005-03-16',
                'broker_id' => $joyride?->broker_id,
                'brand_manager' => 'Henri Rousseau',
                'shipment_type_id' => $air->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-508',
                'brand' => 'Omega',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2005-04-09',
                'broker_id' => $lbc?->broker_id,
                'brand_manager' => 'Elena Moretti',
                'shipment_type_id' => $land->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-509',
                'brand' => 'Cartier',
                'incoterm' => 'FCA',
                'actual_time_of_arrival' => '2005-05-23',
                'broker_id' => $grab?->broker_id,
                'brand_manager' => 'Sophie Dubois',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-510',
                'brand' => 'Patek Philippe',
                'incoterm' => 'FOB',
                'actual_time_of_arrival' => '2005-06-11',
                'broker_id' => $lalancove?->broker_id,
                'brand_manager' => 'Antoine Benoit',
                'shipment_type_id' => $air->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-511',
                'brand' => 'Apple',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2005-07-07',
                'broker_id' => $angkas?->broker_id,
                'brand_manager' => 'Timothy Cook',
                'shipment_type_id' => $land->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-512',
                'brand' => 'Samsung',
                'incoterm' => 'FCA',
                'actual_time_of_arrival' => '2005-08-19',
                'broker_id' => $movelt?->broker_id,
                'brand_manager' => 'Min-Hee Lee',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-513',
                'brand' => 'Mercedes Benz',
                'incoterm' => 'FOB',
                'actual_time_of_arrival' => '2005-09-04',
                'broker_id' => $joyride?->broker_id,
                'brand_manager' => 'Klaus Mueller',
                'shipment_type_id' => $air->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-514',
                'brand' => 'BMW',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2005-10-21',
                'broker_id' => $lbc?->broker_id,
                'brand_manager' => 'Hans Schmidt',
                'shipment_type_id' => $land->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-515',
                'brand' => 'Porsche',
                'incoterm' => 'FCA',
                'actual_time_of_arrival' => '2005-11-13',
                'broker_id' => $grab?->broker_id,
                'brand_manager' => 'Dieter Hoffman',
                'shipment_type_id' => $sea->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-516',
                'brand' => 'Lamborghini',
                'incoterm' => 'FOB',
                'actual_time_of_arrival' => '2005-12-02',
                'broker_id' => $lalancove?->broker_id,
                'brand_manager' => 'Marco Rossi',
                'shipment_type_id' => $air->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'year' => 2025,
                'month' => 4,
                'shipment_reference' => '2025-SKDEVAN-517',
                'brand' => 'Ferrari',
                'incoterm' => 'EXW',
                'actual_time_of_arrival' => '2006-01-08',
                'broker_id' => $angkas?->broker_id,
                'brand_manager' => 'Giancarlo Visconti',
                'shipment_type_id' => $land->shipment_type_id,
                'status_id' => $pending->status_id,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($shipments as $shipment) {
            Shipment::create($shipment);
        }
    }
}
